### ISSUE TITLE
性能好像不太理想呀

### ISSUE THREAD

**Issue by ZooYuu** [fukuball/jieba-php.fukuball.com#1]
对比其他语言的实现方式，php的这个版本分词或者关键字提取速度有点慢呀，每次处理都要5s以上的，并且是在文本长度很小的情况下（20个中文以下的长度）

**Comment by fukuball** [comment]
只有在第一次載入字典時需要 5s，後續處理則不需這樣的時間，如果要做資料分析，應該盡量避免直接線上調用，這只是一個簡單展示，真正 production 不會這樣用的
